version: '2'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "5173:5173"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"  
