version: "2"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app/client # Mount only client directory
    ports:
      - "5173:5173"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app/server # Mount only server directory
    ports:
      - "5000:5000"
